# fly.toml app configuration file generated for fullstack-part11-phonebook on 2024-01-02T14:54:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack-part11-phonebook"
primary_region = "arn"

[deploy]
  release_command = "npm run build:ui"

[processes]
  app = "node index.js"

[build]
  [build.args]
    NODE_VERSION = "20.6.1"  

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
